global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: jenkins
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: gitea
    metrics_path: /metrics
    static_configs:
      - targets: ['gitea:3000']

  - job_name: 'front_blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://front.dsp5-archi-f24a-15m-g4-2025-akf.fr/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
