global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: ['traefik:9100']

  - job_name: jenkins
    metrics_path: /prometheus
    basic_auth:
      username: admin
      password: changeMe
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
